# Generated by Django 4.1.2 on 2022-11-14 18:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[users.validators.check_birthdate]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Регистрация с домена rambler запрещена', regex='@rambler.ru')], verbose_name='email address'),
        ),
    ]
