# Generated by Django 4.1.2 on 2022-11-14 20:06

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthdate_alter_user_age_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(validators=[users.validators.check_birthdate]),
        ),
    ]
