# Generated by Django 4.1.2 on 2022-10-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ctegory',
            new_name='Category',
        ),
    ]
